language: go
go:
- "1.10"

before_install:
  - go get -t -v ./...


script:
  - ./runtest.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com

